#!/usr/bin/env bash
# Sync Glass theme colors from Material You palette
COLORS_JSON="$HOME/.cache/wal/colors.json"
THEME="$HOME/tauon/user-data/theme/Glass.ttheme"

[ ! -f "$COLORS_JSON" ] && exit 1

python3 << 'PYEOF'
import json

import os
d = json.load(open(os.environ["HOME"] + "/.cache/wal/colors.json"))
c = d["colors"]

def hex2rgb(h):
    h = h.lstrip("#")
    return f"{int(h[0:2],16)},{int(h[2:4],16)},{int(h[4:6],16)}"

def dim(h, factor=0.4):
    h = h.lstrip("#")
    r,g,b = int(h[0:2],16), int(h[2:4],16), int(h[4:6],16)
    return f"{min(255,int(r*factor))},{min(255,int(g*factor))},{min(255,int(b*factor))}"

bg = dim(d["special"]["background"], 0.8)
primary = hex2rgb(c["color4"])
secondary = hex2rgb(c["color5"])
accent = hex2rgb(c["color6"])
fg = hex2rgb(d["special"]["foreground"])
dimmed = hex2rgb(c["color8"])

theme = f"""# Glass - Auto-synced from Material You
# Generated by sync-theme.sh

{bg}\t\t\tplayer background (top panel)
{bg}\t\t\tplaylist panel
{bg}\t\t\tside panel
{bg}\t\t\tbottom panel
{bg}\t\t\tgallery background
{bg}\t\t\tqueue panel
{dim(d["special"]["background"], 1.2)}\t\t\tcolumn bar background

# Playlist text
{fg}\t\t\ttrack line
{dimmed}\t\t\ttrack time
{dim(d["special"]["foreground"], 0.4)}\t\t\ttrack index
{dim(d["special"]["foreground"], 0.8)}\t\t\ttrack artist
{dim(d["special"]["foreground"], 0.6)}\t\t\talbum line

# Playing track
{primary}\t\t\ttrack playing
{primary}\t\t\tindex playing
{dim(c["color4"], 1.3)}\t\t\tartist playing
{dim(c["color4"], 0.9)}\t\t\talbum playing
{primary}\t\t\ttime playing

# States
90,90,110\t\t\ttrack missing
243,139,168\t\t\tfav line
{primary}\t\t\tfolder line
{fg}\t\t\tfolder title

# Highlights
{primary},30\t\t\tplaying highlight
{primary},22\t\t\tselect highlight
{primary},25\t\t\tgallery highlight

# Bottom panel
{dimmed}\t\t\tbuttons off
{primary}\t\t\tbuttons over
{primary}\t\t\tbuttons active
{fg}\t\t\tplaying time
{primary}\t\t\tseek bar
{primary}\t\t\tvolume bar
{dim(d["special"]["background"], 1.5)}\t\t\tseek bg
{dim(d["special"]["background"], 1.5)}\t\t\tvolume bg
{dim(d["special"]["foreground"], 0.3)}\t\t\tscroll bar
{dimmed}\t\t\tmode off
{dim(d["special"]["foreground"], 0.7)}\t\t\tmode over
{primary}\t\t\tmode on
{fg}\t\t\tbottom title

# Menus
{bg}\t\t\tmenu background
{dim(d["special"]["foreground"], 0.25)}\t\t\tmenu border
{primary},25\t\t\tmenu highlight
{fg}\t\t\tmenu text
{dimmed}\t\t\tmenu disable text
{primary}\t\t\tmenu icons

# Dialog boxes
{bg}\t\t\tbox background
{dim(d["special"]["foreground"], 0.25)}\t\t\tbox border
{fg}\t\t\tbox title text
{dim(d["special"]["foreground"], 0.7)}\t\t\tbox text label
{fg}\t\t\tbox text normal
{dimmed}\t\t\tbox sub text
{fg}\t\t\tbox input text
{dim(d["special"]["foreground"], 0.3)}\t\t\tbox text border
{fg}\t\t\tbox button text normal
{dim(d["special"]["background"], 1.5)}\t\t\tbox button background normal
{primary}\t\t\tbox button background highlight

# Tabs
{primary}\t\t\ttab active line
{dimmed}\t\t\ttab line
{bg}\t\t\ttab background
{dim(d["special"]["background"], 1.5)}\t\t\ttab over
{dim(d["special"]["background"], 1.2)}\t\t\ttab active background
{primary}\t\t\tmusic vis

# Side panel
{fg}\t\t\ttitle info
{dim(d["special"]["foreground"], 0.7)}\t\t\textra info
{dim(d["special"]["foreground"], 0.25)}\t\t\tart border

# Mini
{bg}\t\t\tmini bg
{dim(d["special"]["foreground"], 0.25)}\t\t\tmini border
{fg}\t\t\tmini text 1
{dim(d["special"]["foreground"], 0.7)}\t\t\tmini text 2

# Bio
{bg}\t\t\tartist bio background
{fg}\t\t\tartist bio text
"""

with open(os.environ["HOME"] + "/tauon/user-data/theme/Glass.ttheme", "w") as f:
    f.write(theme)
print("Theme synced")
PYEOF
